# Generated by Django 5.0.4 on 2024-04-29 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название')),
                ('product_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение')),
                ('product_price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата записи')),
                ('updated_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата последнего изменения')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
