# Generated by Django 5.0.4 on 2024-06-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение категории'),
        ),
    ]
